latent: False

annealing_scheduler_config:
  num_steps: 200
  sigma_max: 100
  sigma_min: 0.1
  sigma_final: 0
  schedule: 'linear'
  timestep: 'poly-7'

diffusion_scheduler_config:
  num_steps: 5
  sigma_min: 0.01
  sigma_final: 0
  schedule: 'linear'
  timestep: 'poly-7'
